Controllers/CanvasController.cs
using Microsoft.AspNetCore.Mvc;
using FinalBattle.Models;
using System.Threading.Tasks;
using FinalBattle.ViewModels;
using FinalBattle;
using FinalBattle.Interfaces;

public class CanvasController : Controller
{
    private readonly ICanvasRepository _canvasRepository;
    private readonly IPhotoService _photoService;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public CanvasController(ICanvasRepository canvasRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
    {
        _canvasRepository = canvasRepository;
        _photoService = photoService;
        _httpContextAccessor = httpContextAccessor;
    }

    // 显示画布列表
    public async Task<IActionResult> Index()
    {
        var canvases = await _canvasRepository.GetAllCanvasesAsync();
        return View(canvases);
    }

    // 显示添加画布的表单
    public IActionResult Create()
    {
        var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
        var createCanvasViewModel = new CreateCanvasViewModel { UserId = curUserId };
        return View(createCanvasViewModel);
        
    }

    // 处理添加画布的表单提交
    //这个注释看起来有点淡  但是没有到费眼睛的底部
    [HttpPost]
    public async Task<IActionResult> Create(CreateCanvasViewModel canvasVM)
    {
        if (ModelState.IsValid)
        {
            byte[] imageBytes = Convert.FromBase64String(canvasVM.Data);
            var canvas = new Canvas
            {
                Title = canvasVM.Title,

                Data = imageBytes,
                UserId = canvasVM.UserId,
                CreationTime = DateTime.Now,
            };
            _canvasRepository.CreateCanvasAsync(canvas);
            return RedirectToAction("Index");
        }
        else
        {
            ModelState.AddModelError("", "photo-upload-failed");
        }
        return View(canvasVM);
    }


}

Controllers/EmailController.cs
using FinalBattle.Interfaces;
using FinalBattle.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FinalBattle.Controllers
{
    public class EmailController : Controller
    {
        private readonly IEmailService _emailService;

        public EmailController(IEmailService emailService)
        {
            _emailService = emailService;
        }

        public IActionResult SendEmail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendEmail(SendEmailViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _emailService.SendEmailAsync(model.Sender, model.Receiver, model.Subject, model.Message, model.Attachments);
                return RedirectToAction("SendEmailSuccess");
            }

            return View(model);
        }

        public IActionResult SendEmailSuccess()
        {
            return View();
        }
    }
}

Controllers/PostController.cs
using FinalBattle.Interfaces;
using FinalBattle.Models;
using FinalBattle.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net;

namespace FinalBattle.Controllers
{
    public class PostController : Controller
    {

        //这里需要用到爱情
        private readonly IPhotoService _photoService;
        private readonly IPostRepository _postRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PostController(IPostRepository postRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {

            _postRepository = postRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }


        public async Task<IActionResult> Index()
        {
            IEnumerable<Post> lists = await _postRepository.GetAll();
            return View(lists);
        }

        public async Task<IActionResult> Detail(int id)
        {

            Post post = await _postRepository.GetByIdAsync(id);
            return View(post);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createPostViewModel = new CreatePostViewModel { UserId = curUserId };
            return View(createPostViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostViewModel postVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(postVM.CoverImageUrl);
                var post = new Post
                {
                    Title = postVM.Title,
                    Body = postVM.Body,
                    CoverImageUrl = result.Url.ToString(),
                    PostCategory = postVM.PostCategory,
                    UserId = postVM.UserId,
                    PublishDate=DateTime.Now,
                    //Address = new Address
                    //{
                    //    Street = clubVM.Address.Street,
                    //    City = clubVM.Address.City,
                    //    State = clubVM.Address.State,
                    //}
                };
                _postRepository.Add(post);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "photo-upload-failed");
            }
            return View(postVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var post = await _postRepository.GetByIdAsync(id);
            if (post == null) return View("Error");
            var postVM = new EditPostViewModel
            {
                Title = post.Title,
                Body = post.Body,
                URL = post.CoverImageUrl,
                PostCategory = post.PostCategory,
                PublishDate = DateTime.Now,
            };
            return View(postVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditPostViewModel postVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit post");
                return View("Edit", postVM);
            }
            var userPost = await _postRepository.GetByIdAsyncNoTracking(id);

            if (userPost != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userPost.CoverImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "can not delete photo");
                    return View(postVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(postVM.Image);

                var post = new Post
                {
                    Id = id,
                    Title = postVM.Title,
                    Body = postVM.Body,
                    CoverImageUrl = photoResult.Url.ToString(),
                    PostCategory = postVM.PostCategory,
                PublishDate = DateTime.Now,
                };

                _postRepository.Update(post);
                return RedirectToAction("Index");
            }
            else
            {
                return View(postVM);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _postRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var postDetails = await _postRepository.GetByIdAsync(id);
            if (postDetails == null) return View("Error");

            _postRepository.Delete(postDetails);
            return RedirectToAction("Index");
        }




    }
}

Controllers/UserController.cs
using FinalBattle.Interfaces;
using FinalBattle.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FinalBattle.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        public UserController(IUserRepository userRepository)
        {

            _userRepository = userRepository;

        }

        [HttpGet("users")]
        public async Task<IActionResult> Index()
        {
            var users = await _userRepository.GetAllUsers();

            var result = users.Select(user => new UserViewModel
            {
                Id = user.Id,               
                UserName = user.UserName,
                UserImageUrl = user.UserImageUrl
            }).ToList();

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            var user = await _userRepository.GetUserById(id);
            var userDetailViewModel = new UserDetailViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                
                UserImageUrl = user.UserImageUrl,
                
            };

            return View(userDetailViewModel);

        }
    }
}

Views/Shared/_Layout.cshtml
@* @using System.Security.Claims
@using FinalBattle.Models
@model User *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalBattle</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalBattle.styles.css" asp-append-version="true" />
    <style>
        .nav-item {
            width:90px;
            margin-left: 14px;
            margin-right: 14px;
        }

        .nav-item:hover{
            
            background:pink;
        }

        .navttt{
            margin-right:25px;
           font-size:24px;
           font-weight:600;
            text-decoration:none;
        }
        .nav-link{
            text-align:center;
            font-size:17px;
            font-weight:380;
        }
        .nav-link:hover{
            font-weight:600;
            
        }
        .text-dark:hover{
            color:aquamarine;
        }

        
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3" style="color: black; background-color: white;">
            <div class="container-fluid">
                <a class="navttt" asp-area="" asp-controller="Home" asp-action="Index" style="color: black;">FinalBattle</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between nav-dark text-dark">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">主页</a>
                        </li> *@

                        @* @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Runners</a>
                            </li>

                        } *@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">社区</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResourceMall" asp-action="Index">资源商城</a>
                        </li>
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">个人中心</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">所有用户</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="SendEmail">邮件📧</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Canvas" asp-action="Index">创作🖊</a>
                            </li>

                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button class="btn btn-outline-danger" style="align-content:center;text-align:center;margin-left:20px;">登出</button>
                                </form>
                            </li>

                            

                            <li class="nav-item" style="margin-left:600px">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserCenter">
                                    @* <img src="@Model.UserImageUrl" alt="User Avatar" /> *@
                                </a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">登录</a>
                            </li>                           
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RunGroupWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>