ViewModels/DashboardViewModel.cs
using FinalBattle.Models;

namespace FinalBattle.ViewModels
{
    public class DashboardViewModel
    {
        public List<Post> Posts { get; set; }
        
    }
}

Controllers/DashboardController.cs
using CloudinaryDotNet.Actions;
using FinalBattle.Interfaces;
using FinalBattle.Models;
using FinalBattle.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FinalBattle.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IPhotoService _photoService;
        public DashboardController(IDashboardRepository dashboardRepository, IHttpContextAccessor httpContextAccessor, IPhotoService photoService)
        {
            _dashboardRepository = dashboardRepository;
            _httpContextAccessor = httpContextAccessor;
            _photoService = photoService;

        }

        private void MapUserEdit(User user, EditUserDashboardViewModel editVM, ImageUploadResult photoResult)
        {
            user.Id = editVM.Id;           
            user.UserImageUrl = photoResult.Url.ToString();
            
        }

        public async Task<IActionResult> Index()
        {
            var userPosts = await _dashboardRepository.GetAllUserPosts();            
            var dashboardViewModel = new DashboardViewModel()
            {
                Posts = userPosts,                
            };
            return View(dashboardViewModel);
        }

        public async Task<IActionResult> EditUserProfile()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            User user = await _dashboardRepository.GetUserById(curUserId);
            if (user == null) return View("Error");
            var editUserViewModel = new EditUserDashboardViewModel()
            {
                Id = curUserId,
                
                UserImageUrl = user.UserImageUrl,
                
            };
            return View(editUserViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserProfile(EditUserDashboardViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "failed to edit profile");
                return View("EditUserProfile", editVM);
            }
            User user = await _dashboardRepository.GetByIdNoTracking(editVM.Id);
            if (user.UserImageUrl == "" || user.UserImageUrl == null)
            {
                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);
                MapUserEdit(user, editVM, photoResult);
                _dashboardRepository.Update(user);
                return RedirectToAction("Index");
            }
            else
            {
                try
                {
                    await _photoService.DeletePhotoAsync(user.UserImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "could not delete photo");
                    return View(editVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRepository.Update(user);

                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/PostController.cs
using FinalBattle.Interfaces;
using FinalBattle.Models;
using FinalBattle.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net;

namespace FinalBattle.Controllers
{
    public class PostController : Controller
    {

        //这里需要用到爱情
        private readonly IPhotoService _photoService;
        private readonly IPostRepository _postRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PostController(IPostRepository postRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {

            _postRepository = postRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }


        public async Task<IActionResult> Index()
        {
            IEnumerable<Post> lists = await _postRepository.GetAll();
            return View(lists);
        }

        public async Task<IActionResult> Detail(int id)
        {

            Post post = await _postRepository.GetByIdAsync(id);
            return View(post);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createPostViewModel = new CreatePostViewModel { UserId = curUserId };
            return View(createPostViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostViewModel postVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(postVM.CoverImageUrl);
                var post = new Post
                {
                    Title = postVM.Title,
                    Body = postVM.Body,
                    CoverImageUrl = result.Url.ToString(),
                    PostCategory = postVM.PostCategory,
                    UserId = postVM.UserId,
                    PublishDate=DateTime.Now,
                    //Address = new Address
                    //{
                    //    Street = clubVM.Address.Street,
                    //    City = clubVM.Address.City,
                    //    State = clubVM.Address.State,
                    //}
                };
                _postRepository.Add(post);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "photo-upload-failed");
            }
            return View(postVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var post = await _postRepository.GetByIdAsync(id);
            if (post == null) return View("Error");
            var postVM = new EditPostViewModel
            {
                Title = post.Title,
                Body = post.Body,
                URL = post.CoverImageUrl,
                PostCategory = post.PostCategory,
                PublishDate = DateTime.Now,
            };
            return View(postVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditPostViewModel postVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit post");
                return View("Edit", postVM);
            }
            var userPost = await _postRepository.GetByIdAsyncNoTracking(id);

            if (userPost != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userPost.CoverImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "can not delete photo");
                    return View(postVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(postVM.Image);

                var post = new Post
                {
                    Id = id,
                    Title = postVM.Title,
                    Body = postVM.Body,
                    CoverImageUrl = photoResult.Url.ToString(),
                    PostCategory = postVM.PostCategory,
                PublishDate = DateTime.Now,
                };

                _postRepository.Update(post);
                return RedirectToAction("Index");
            }
            else
            {
                return View(postVM);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _postRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var postDetails = await _postRepository.GetByIdAsync(id);
            if (postDetails == null) return View("Error");

            _postRepository.Delete(postDetails);
            return RedirectToAction("Index");
        }




    }
}

Views/Dashboard/EditUserProfile.cshtml
@using FinalBattle.ViewModels
@model EditUserDashboardViewModel



<form method="post" asp-action="EditUserProfile" enctype="multipart/form-data">
    <input type="hidden" id="Id" name="Id" asp-for="Id" />
    @* <div class="form-group">
        <label asp-for="Pace">Pace</label>
        <input asp-for="Pace" class="form-control" placeholder="Pace">
        <span asp-validation-for="Pace" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Mileage">Mileage</label>
        <input asp-for="Mileage" class="form-control" placeholder="Mileage">
        <span asp-validation-for="Mileage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="City">City</label>
        <input asp-for="City" class="form-control" placeholder="City">
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="State">State</label>
        <input asp-for="State" class="form-control" placeholder="State">
        <span asp-validation-for="State" class="text-danger"></span>
    </div> *@
    <div class="form-group">
        <label asp-for="Image">Profile Image</label>
        <input asp-for="Image" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">确认修改</button>

</form>

Views/Dashboard/Index.cshtml
* @using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

@model FinalBattle.ViewModels.DashboardViewModel


<h1 class="display-4 fw-normal">孤独的角落</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Post" asp-action="Create">立刻发帖</a>

<a type="button" class="btn btn-primary" asp-area="" asp-controller="Dashboard" asp-action="EditUserProfile">编辑个人信息</a>
<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">历史发帖</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Posts)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.CoverImageUrl" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Body</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Post" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <a asp-controller="Post" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>



                                        <a asp-controller="Post" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.PostCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
       
    </div>
</div> 